### ISSUE TITLE
The default scaling in Windows 11 causes breakpoints to display inaccurately

### ISSUE THREAD

**Issue by DAOLOGE** [mvrlin/nuxt-viewport#88]
The default scaling in Windows 11 is 150%, which causes page breakpoints to have a 1.5-pixel deviation. When the system settings are restored to 100% scale, the breakpoints work normally. Due to my limited technical skills, I don't know how to solve this problem, but when using the useBreakpoints from vueuse, the breakpoints work normally at 150% scaling.

**Comment by DAOLOGE** [comment]
Hello, this is a minimal reproduction, thank you very much for making this module
reproduction: https://stackblitz.com/edit/github-fbfat99l?file=app.vue
video: https://github.com/user-attachments/assets/54286107-82d3-4839-821a-0f1985b9a19c

**Comment by mvrlin** [comment]
Hey! Thanks for the bug report. I'll take a look as soon as possible.

**Comment by mvrlin** [comment]
@DAOLOGE I think I fixed it, can you test please?
https://stackblitz.com/github/mvrlin/nuxt-viewport/tree/scaling

**Comment by DAOLOGE** [comment]
> [@DAOLOGE](https://github.com/DAOLOGE)我想我修复了它，你能测试一下吗？ https://stackblitz.com/github/mvrlin/nuxt-viewport/tree/scaling

Hello, it works perfectly, thank you very much for fixing it in such a short time, you are awesome

**Comment by DAOLOGE** [comment]
> [@DAOLOGE](https://github.com/DAOLOGE) I think I fixed it, can you test please? https://stackblitz.com/github/mvrlin/nuxt-viewport/tree/scaling

Hello, it works normally with my system default setting at 150% scaling, but under this solution if I change the system scaling setting to 175%, the problem appears again. My monitor default setting is 150% scaling, maybe some monitors or laptops use 125% or other scaling ratios, the problem would still occur

**Comment by mvrlin** [comment]
@DAOLOGE Hmm, okay. I'll take a look.

**Comment by mvrlin** [comment]
@DAOLOGE Can you check again? I used `vueuse` delta value
https://stackblitz.com/github/mvrlin/nuxt-viewport/tree/scaling

**Comment by DAOLOGE** [comment]
> [@DAOLOGE](https://github.com/DAOLOGE) Can you check again? I used `vueuse` delta value https://stackblitz.com/github/mvrlin/nuxt-viewport/tree/scaling

I tested all system scaling values, 100%-350%, everything works normally. Thank you very much for your work on this.

**Comment by mvrlin** [comment]
@DAOLOGE https://www.npmjs.com/package/nuxt-viewport/v/2.3.1 available in the latest release
